/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GuidesRouteImport } from './routes/guides'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WikiRouteImport } from './routes/wiki'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as GuidesSlugRouteImport } from './routes/guides/$slug'
import { Route as GuidesBeginnerRouteImport } from './routes/guides/beginner'
import { Route as GuidesMapRouteImport } from './routes/guides/map'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as WikiCategoryRouteImport } from './routes/wiki/$category'
import { Route as WikiCategoryIndexRouteImport } from './routes/wiki/$category/index'
import { Route as WikiCategoryEntryRouteImport } from './routes/wiki/$category/$entry'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesRoute = GuidesRouteImport.update({
  id: '/guides',
  path: '/guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRoute = WikiRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesSlugRoute = GuidesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesBeginnerRoute = GuidesBeginnerRouteImport.update({
  id: '/beginner',
  path: '/beginner',
  getParentRoute: () => GuidesRoute,
} as any)
const GuidesMapRoute = GuidesMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => GuidesRoute,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRoute,
} as any)
const WikiCategoryRoute = WikiCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => WikiRoute,
} as any)
const WikiCategoryIndexRoute = WikiCategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiCategoryRoute,
} as any)
const WikiCategoryEntryRoute = WikiCategoryEntryRouteImport.update({
  id: '/$entry',
  path: '/$entry',
  getParentRoute: () => WikiCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/guides': typeof GuidesRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiki': typeof WikiRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/beginner': typeof GuidesBeginnerRoute
  '/guides/map': typeof GuidesMapRoute
  '/wiki/$category': typeof WikiCategoryRouteWithChildren
  '/guides/': typeof GuidesIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$category/$entry': typeof WikiCategoryEntryRoute
  '/wiki/$category/': typeof WikiCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/beginner': typeof GuidesBeginnerRoute
  '/guides/map': typeof GuidesMapRoute
  '/guides': typeof GuidesIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/wiki/$category/$entry': typeof WikiCategoryEntryRoute
  '/wiki/$category': typeof WikiCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/guides': typeof GuidesRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/wiki': typeof WikiRouteWithChildren
  '/guides/$slug': typeof GuidesSlugRoute
  '/guides/beginner': typeof GuidesBeginnerRoute
  '/guides/map': typeof GuidesMapRoute
  '/wiki/$category': typeof WikiCategoryRouteWithChildren
  '/guides/': typeof GuidesIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/wiki/$category/$entry': typeof WikiCategoryEntryRoute
  '/wiki/$category/': typeof WikiCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/guides'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/wiki'
    | '/guides/$slug'
    | '/guides/beginner'
    | '/guides/map'
    | '/wiki/$category'
    | '/guides/'
    | '/wiki/'
    | '/wiki/$category/$entry'
    | '/wiki/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/guides/$slug'
    | '/guides/beginner'
    | '/guides/map'
    | '/guides'
    | '/wiki'
    | '/wiki/$category/$entry'
    | '/wiki/$category'
  id:
    | '__root__'
    | '/'
    | '/guides'
    | '/manifest.webmanifest'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/wiki'
    | '/guides/$slug'
    | '/guides/beginner'
    | '/guides/map'
    | '/wiki/$category'
    | '/guides/'
    | '/wiki/'
    | '/wiki/$category/$entry'
    | '/wiki/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GuidesRoute: typeof GuidesRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WikiRoute: typeof WikiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides': {
      id: '/guides'
      path: '/guides'
      fullPath: '/guides'
      preLoaderRoute: typeof GuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/$slug': {
      id: '/guides/$slug'
      path: '/$slug'
      fullPath: '/guides/$slug'
      preLoaderRoute: typeof GuidesSlugRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/beginner': {
      id: '/guides/beginner'
      path: '/beginner'
      fullPath: '/guides/beginner'
      preLoaderRoute: typeof GuidesBeginnerRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/guides/map': {
      id: '/guides/map'
      path: '/map'
      fullPath: '/guides/map'
      preLoaderRoute: typeof GuidesMapRouteImport
      parentRoute: typeof GuidesRoute
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/$category': {
      id: '/wiki/$category'
      path: '/$category'
      fullPath: '/wiki/$category'
      preLoaderRoute: typeof WikiCategoryRouteImport
      parentRoute: typeof WikiRoute
    }
    '/wiki/$category/': {
      id: '/wiki/$category/'
      path: '/'
      fullPath: '/wiki/$category/'
      preLoaderRoute: typeof WikiCategoryIndexRouteImport
      parentRoute: typeof WikiCategoryRoute
    }
    '/wiki/$category/$entry': {
      id: '/wiki/$category/$entry'
      path: '/$entry'
      fullPath: '/wiki/$category/$entry'
      preLoaderRoute: typeof WikiCategoryEntryRouteImport
      parentRoute: typeof WikiCategoryRoute
    }
  }
}

interface GuidesRouteChildren {
  GuidesSlugRoute: typeof GuidesSlugRoute
  GuidesBeginnerRoute: typeof GuidesBeginnerRoute
  GuidesMapRoute: typeof GuidesMapRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

const GuidesRouteChildren: GuidesRouteChildren = {
  GuidesSlugRoute: GuidesSlugRoute,
  GuidesBeginnerRoute: GuidesBeginnerRoute,
  GuidesMapRoute: GuidesMapRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}

const GuidesRouteWithChildren =
  GuidesRoute._addFileChildren(GuidesRouteChildren)

interface WikiCategoryRouteChildren {
  WikiCategoryEntryRoute: typeof WikiCategoryEntryRoute
  WikiCategoryIndexRoute: typeof WikiCategoryIndexRoute
}

const WikiCategoryRouteChildren: WikiCategoryRouteChildren = {
  WikiCategoryEntryRoute: WikiCategoryEntryRoute,
  WikiCategoryIndexRoute: WikiCategoryIndexRoute,
}

const WikiCategoryRouteWithChildren = WikiCategoryRoute._addFileChildren(
  WikiCategoryRouteChildren,
)

interface WikiRouteChildren {
  WikiCategoryRoute: typeof WikiCategoryRouteWithChildren
  WikiIndexRoute: typeof WikiIndexRoute
}

const WikiRouteChildren: WikiRouteChildren = {
  WikiCategoryRoute: WikiCategoryRouteWithChildren,
  WikiIndexRoute: WikiIndexRoute,
}

const WikiRouteWithChildren = WikiRoute._addFileChildren(WikiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GuidesRoute: GuidesRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WikiRoute: WikiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
